option('plugin_directory', description: 'Location used to look for plugin (default: ${prefix}/lib/kylin-wlcom/plugins/)', type: 'string', value: '')
option('examples', type: 'boolean', value: true, description: 'Build example applications')
option('nls', type: 'feature', value: 'auto', description: 'Enable native language support')
option('kde_output', type: 'boolean', value: true, description: 'Enable kde output protocols support')
option('kde_virtual_desktop', type: 'boolean', value: true, description: 'Enable kde virtual desktop protocol support')
option('wlr_output', type: 'boolean', value: true, description: 'Enable wlroots output protocols support')
option('wlr_scene', type: 'boolean', value: false, description: 'Enable wlroots scene as default')
option('wlr_foreign_toplevel', type: 'boolean', value: true, description: 'Enable wlroots foreign toplevel protocol support')
option('wlr_layer_shell', type: 'boolean', value: true, description: 'Enable wlroots layer shell protocol support')
option('kde_global_accel', type: 'boolean', value: true, description: 'Enable kde global accel dbus server support')
option('kde_input', type: 'boolean', value: true, description: 'Enable kde input dbus server support')
option('kde_nightcolor', type: 'boolean', value: true, description: 'Enable kde colorcorrect dbus server support')
option('kde_plasma_shell', type: 'boolean', value: true, description: 'Enable kde plasma shell protocol support')
option('kde_plasma_window_management', type: 'boolean', value: true, description: 'Enable kde plasma window management protocol support')
option('kde_blur', type: 'boolean', value: true, description: 'Enable kde blur protocol support')
option('kde_global_settings', type: 'boolean', value: true, description: 'Enable kde global settings dbus server support')
option('ukui_screenshot', type: 'boolean', value: true, description: 'Enable ukui screenshot dbus server support')
