crypto = dependency('openssl')
wlcom_deps += crypto

wlcom_sources += files(
  'dbus.c',
  'debug.c',
  'file.c',
  'hash_table.c',
  'identifier.c',
  'limit.c',
  'logger.c',
  'matrix.c',
  'vec2.c',
  'queue.c',
  'quirks.c',
  'region.c',
  'spawn.c',
  'string.c',
  'sysfs.c',
  'time.c',
  'wayland.c',
)
