// SPDX-FileCopyrightText: 2023 KylinSoft Co., Ltd.
//
// SPDX-License-Identifier: MulanPSL-2.0

#include <wlr/backend/drm.h>
#include <xf86drmMode.h>

#include "output_p.h"

/* Generated by gen-default-modes.py */

static const drmModeModeInfo meta_default_landscape_drm_mode_infos[] = {
    { 38250, 800, 832, 912, 1024, 0, 600, 603, 607, 624, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "800x600_60.00" },
    { 63500, 1024, 1072, 1176, 1328, 0, 768, 771, 775, 798, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1024x768_60.00" },
    { 83500, 1280, 1352, 1480, 1680, 0, 800, 803, 809, 831, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1280x800_60.00" },
    { 109000, 1280, 1368, 1496, 1712, 0, 1024, 1027, 1034, 1063, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1280x1024_60.00" },
    { 80000, 1366, 1436, 1577, 1648, 0, 768, 778, 783, 810, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1366x768_59.93" },
    { 106500, 1440, 1528, 1672, 1904, 0, 900, 903, 909, 934, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1440x900_60.00" },
    { 113750, 1440, 1528, 1672, 1904, 0, 960, 963, 973, 996, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1440x960_60.00" },
    { 161000, 1600, 1712, 1880, 2160, 0, 1200, 1203, 1207, 1245, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1600x1200_60.00" },
    { 146250, 1680, 1784, 1960, 2240, 0, 1050, 1053, 1059, 1089, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1680x1050_60.00" },
    { 157000, 1680, 1792, 1968, 2256, 0, 1120, 1123, 1133, 1162, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1680x1120_60.00" },
    { 173000, 1920, 2048, 2248, 2576, 0, 1080, 1083, 1088, 1120, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1920x1080_60.00" },
    { 206250, 1920, 2056, 2256, 2592, 0, 1280, 1283, 1293, 1327, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "1920x1280_60.00" },
    { 263500, 2160, 2320, 2552, 2944, 0, 1440, 1443, 1453, 1493, 0, 0,
      DRM_MODE_FLAG_NHSYNC | DRM_MODE_FLAG_PVSYNC, DRM_MODE_TYPE_USERDEF, "2160x1440_60.00" },
};

static const drmModeModeInfo meta_default_portrait_drm_mode_infos[] = {
    { 38250, 600, 603, 607, 624, 0, 800, 832, 912, 1024, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "600x800_60.00" },
    { 63500, 768, 771, 775, 798, 0, 1024, 1072, 1176, 1328, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "768x1024_60.00" },
    { 83500, 800, 803, 809, 831, 0, 1280, 1352, 1480, 1680, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "800x1280_60.00" },
    { 85250, 768, 771, 781, 798, 0, 1368, 1440, 1576, 1784, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "768x1368_60.00" },
    { 106500, 900, 903, 909, 934, 0, 1440, 1528, 1672, 1904, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "900x1440_60.00" },
    { 113750, 960, 963, 973, 996, 0, 1440, 1528, 1672, 1904, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "960x1440_60.00" },
    { 161000, 1200, 1203, 1207, 1245, 0, 1600, 1712, 1880, 2160, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "1200x1600_60.00" },
    { 146250, 1050, 1053, 1059, 1089, 0, 1680, 1784, 1960, 2240, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "1050x1680_60.00" },
    { 157000, 1120, 1123, 1133, 1162, 0, 1680, 1792, 1968, 2256, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "1120x1680_60.00" },
    { 173000, 1080, 1083, 1088, 1120, 0, 1920, 2048, 2248, 2576, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "1080x1920_60.00" },
    { 206250, 1280, 1283, 1293, 1327, 0, 1920, 2056, 2256, 2592, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "1280x1920_60.00" },
    { 263500, 1440, 1443, 1453, 1493, 0, 2160, 2320, 2552, 2944, 0, 0,
      DRM_MODE_FLAG_PHSYNC | DRM_MODE_FLAG_NVSYNC, DRM_MODE_TYPE_USERDEF, "1440x2160_60.00" },
};

static bool check_mode_is_exist(struct wlr_output *output, const drmModeModeInfo *drm_mod)
{
    struct wlr_output_mode *mode;
    wl_list_for_each(mode, &output->modes, link) {
        if (mode->width == drm_mod->hdisplay && mode->height == drm_mod->vdisplay) {
            return true;
        }
    }

    return false;
}

void output_add_common_modes(struct output *output)
{
    struct wlr_output *wlr_output = output->wlr_output;
    if (!wlr_backend_is_drm(wlr_output->backend)) {
        return;
    }

    /* add more modes for eDP LVDS panel */
    if (strncmp(output->base.name, "eDP", 3) && strncmp(output->base.name, "LVDS", 4)) {
        return;
    }

    int hdisplay = 0;
    int vdisplay = 0;

    struct wlr_output_mode *mode;
    /* only one same resolution continue to add common modes */
    wl_list_for_each(mode, &wlr_output->modes, link) {
        if (hdisplay == 0 && vdisplay == 0) {
            hdisplay = mode->width;
            vdisplay = mode->height;
            continue;
        }
        if (hdisplay != mode->width && vdisplay != mode->height) {
            return;
        }
    }

    if (hdisplay > vdisplay) {
        int mode_lens = sizeof(meta_default_landscape_drm_mode_infos) /
                        sizeof(meta_default_landscape_drm_mode_infos[0]);
        for (int i = 0; i < mode_lens; ++i) {
            const drmModeModeInfo *mod = &meta_default_landscape_drm_mode_infos[i];
            if (hdisplay < mod->hdisplay || vdisplay < mod->vdisplay) {
                continue;
            }

            if (!check_mode_is_exist(wlr_output, mod)) {
                if (!wlr_drm_connector_add_mode(wlr_output, mod)) {
                    kywc_log(KYWC_ERROR, "add common mode(landscape) failed");
                }
            }
        }
    } else {
        int mode_lens = sizeof(meta_default_portrait_drm_mode_infos) /
                        sizeof(meta_default_portrait_drm_mode_infos[0]);
        for (int i = 0; i < mode_lens; ++i) {
            const drmModeModeInfo *mod = &meta_default_portrait_drm_mode_infos[i];
            if (hdisplay < mod->hdisplay || vdisplay < mod->vdisplay) {
                continue;
            }

            if (!check_mode_is_exist(wlr_output, mod)) {
                if (!wlr_drm_connector_add_mode(wlr_output, mod)) {
                    kywc_log(KYWC_ERROR, "add common mode(portrait) failed");
                }
            }
        }
    }
}
