wlcom_sources = files(
    'main.c',
    'server.c',

    'config/common.c',
    'config/config.c',

    'output/config.c',
    'output/output.c',
    'output/layout.c',

    'input/binding.c',
    'input/config.c',
    'input/cursor.c',
    'input/keyboard.c',
    'input/libinput.c',
    'input/input.c',
    'input/monitor.c',
    'input/seat.c',

    'plugin/config.c',
    'plugin/plugin.c',

    'util/global.c',
    'util/identifier.c',
    'util/logger.c',
    'util/spawn.c',
    'util/md5.c',
)

wlcom_sources += files(
    'output/kde_output.c',
)

subdir('adapter')

#subdir('widget')
