wlcom_sources += files(
  'action.c',
  'binding.c',
  'config.c',
  'cursor.c',
  'event.c',
  'gesture.c',
  'idle.c',
  'idle_inhibit.c',
  'input.c',
  'text_input.c',
  'keyboard.c',
  'keyboard_group.c',
  'libinput.c',
  'monitor.c',
  'tablet.c',
  'text_input_v1.c',
  'touch.c',
  'seat.c',
  'selection.c',
)
