wlcom_sources += files(
  'action.c',
  'binding.c',
  'config.c',
  'cursor.c',
  'event.c',
  'gesture.c',
  'idle.c',
  'idle_inhibit.c',
  'input.c',
  'text_input.c',
  'keyboard.c',
  'keyboard_group.c',
  'libinput.c',
  'monitor.c',
  'tablet.c',
  'text_input_v1.c',
  'text_input_v2.c',
  'toplevel_drag.c',
  'touch.c',
  'transient_seat.c',
  'seat.c',
  'selection.c',
)

if have_kde_keystate
  wlcom_sources += files(
    'kde_keystate.c',
  )
endif
